mod tui;
use anyhow::{Context,Result};
use clap::{Parser,Subcommand,ValueEnum};
use std::path::{Path,PathBuf};
use zuri_core::{KnowledgePack,ModelConfig,Severity};

#[derive(Parser)]#[command(name="zuri",version,about="CodeSage Zuri — Offline Code Literacy Engine")]struct Cli{#[command(subcommand)]command:Option<Command>}
#[derive(Subcommand)]enum Command{Index{path:Option<PathBuf>,#[arg(long)]rebuild:bool,#[arg(long)]json:bool},Status{path:Option<PathBuf>,#[arg(long)]json:bool},Map{path:Option<PathBuf>,#[arg(long)]json:bool},Symbols{query:Option<String>,path:Option<PathBuf>,#[arg(long)]json:bool},Explain{target:String,path:Option<PathBuf>,#[arg(long)]json:bool},Trace{target:String,path:Option<PathBuf>,#[arg(long,default_value_t=2)]depth:usize,#[arg(long)]json:bool},Review{path:Option<PathBuf>,#[arg(long)]json:bool,#[arg(long)]severity:Option<SeverityArg>},Why{id:String,path:Option<PathBuf>,#[arg(long)]json:bool},Concepts{target:String,path:Option<PathBuf>,#[arg(long)]json:bool},Search{query:String,#[arg(long,default_value_t=5)]limit:usize,#[arg(long)]json:bool},Learn{topic:String,#[arg(long)]json:bool},Quiz{target:String,path:Option<PathBuf>,#[arg(long)]json:bool},Doctor{#[arg(long)]json:bool},Model{#[command(subcommand)]command:ModelCommand},Tui{path:Option<PathBuf>}}
#[derive(Subcommand)]enum ModelCommand{Status,Configure{#[arg(long)]endpoint:String,#[arg(long)]model:Option<String>,#[arg(long,default_value_t=true)]enabled:bool},Test}
#[derive(Clone,Copy,ValueEnum)]enum SeverityArg{Info,Warning,Error}impl From<SeverityArg> for Severity{fn from(v:SeverityArg)->Self{match v{SeverityArg::Info=>Self::Info,SeverityArg::Warning=>Self::Warning,SeverityArg::Error=>Self::Error}}}
fn root(path:Option<PathBuf>)->Result<PathBuf>{Ok(std::fs::canonicalize(path.unwrap_or(std::env::current_dir()?))?)}
fn db(root:&Path)->Result<zuri_core::ProjectDb>{let d=zuri_core::open_project(root)?;if d.stats()?.files==0{anyhow::bail!("project has no index yet; run `zuri index .` first")}Ok(d)}
fn json<T:serde::Serialize>(v:&T)->Result<()>{println!("{}",serde_json::to_string_pretty(v)?);Ok(())}
fn main()->Result<()>{let cli=Cli::parse();match cli.command.unwrap_or(Command::Tui{path:None}){
Command::Index{path,rebuild,json:j}=>{let r=zuri_core::index_project(&root(path)?,rebuild)?;if j{json(&r)?}else{println!("Indexed {}\nPython files: {}\nParsed: {}  unchanged: {}  removed: {}\nSymbols: {}  findings: {}\nResolved calls: {}  unresolved calls: {}\nNetwork used: no\nModel used: no",r.root.display(),r.python_files,r.parsed_files,r.unchanged_files,r.removed_files,r.stats.symbols,r.stats.findings,r.stats.calls_resolved,r.stats.calls_unresolved)}}
Command::Status{path,json:j}|Command::Map{path,json:j}=>{let r=root(path)?;let d=db(&r)?;let s=d.stats()?;if j{json(&s)?}else{println!("Project: {}\nFiles: {}  symbols: {}  functions/methods: {}  classes: {}\nImports: {}  resolved calls: {}  unresolved calls: {}\nFindings: {}\nIndex: {}",r.display(),s.files,s.symbols,s.functions,s.classes,s.imports,s.calls_resolved,s.calls_unresolved,s.findings,d.path().display())}}
Command::Symbols{query,path,json:j}=>{let v=db(&root(path)?)?.symbols(query.as_deref())?;if j{json(&v)?}else{for s in v{println!("{}\t{}\t{}:{}",s.qualified_name,s.signature,s.location.file,s.location.start_line)}}}
Command::Explain{target,path,json:j}=>{let e=zuri_core::explain(&root(path)?,&target)?;if j{json(&e)?}else{let s=&e.symbol;println!("{}\n{}:{}-{}\n\nSignature\n  {}\n\nStructure\n  branches: {}\n  loops: {}\n  explicit returns: {}\n  exception handlers: {}",s.qualified_name,s.location.file,s.location.start_line,s.location.end_line,s.signature,s.metrics.branches,s.metrics.loops,s.metrics.returns,s.metrics.exception_handlers);if !e.callees.is_empty(){println!("\nCalls");for x in &e.callees{println!("  {} [{:?}] {}:{}",x.name,x.resolution,x.file,x.line)}}if !s.concepts.is_empty(){println!("\nConcepts\n  {}",s.concepts.join("\n  "))}println!("\nEvidence");for(k,v)in e.evidence_summary{println!("  {k}: {v}")}}}
Command::Trace{target,path,depth,json:j}=>{let v=zuri_core::trace(&root(path)?,&target,depth)?;if j{json(&v)?}else{for n in v{println!("{}{} [{:?}] {}:{}","  ".repeat(n.depth),n.name,n.resolution,n.file,n.line)}}}
Command::Review{path,json:j,severity}=>{let mut v=db(&root(path)?)?.findings()?;if let Some(s)=severity{let min:Severity=s.into();v.retain(|f|f.severity>=min)}if j{json(&v)?}else{if v.is_empty(){println!("No current deterministic findings.")}for f in v{println!("{}  {}  {}:{}\n  {} [{} / {}]\n",f.id,f.rule_id,f.location.file,f.location.start_line,f.title,f.evidence,f.confidence)}}}
Command::Why{id,path,json:j}=>{let f=db(&root(path)?)?.finding(&id)?.context("finding not found")?;if j{json(&f)?}else{println!("{} — {}\n{}:{}\nSeverity: {}\nEvidence: {} / {}\n\n{}",f.rule_id,f.title,f.location.file,f.location.start_line,f.severity,f.evidence,f.confidence,f.description);if let Some(r)=f.remediation{println!("\nSuggested remediation\n{r}")}}}
Command::Concepts{target,path,json:j}=>{let v=zuri_core::concepts(&root(path)?,&target)?;if j{json(&v)?}else{for x in v{println!("- {x}")}}}
Command::Search{query,limit,json:j}=>{let p=KnowledgePack::ensure_builtin()?;let v=p.search(&query,limit)?;if j{json(&v)?}else{for h in v{println!("{} — {}\n  {}\n  source: {} ({})\n",h.entry.entry_id,h.entry.title,h.entry.body,h.entry.source_url,h.entry.source_status)}}}
Command::Learn{topic,json:j}=>{let v=KnowledgePack::ensure_builtin()?.topic(&topic)?;if v.is_empty(){anyhow::bail!("no installed Python Core entry for `{topic}`")}if j{json(&v)?}else{for e in v{println!("{}\n{}\n\nSource: {}\nStatus: {}\n",e.title,e.body,e.source_url,e.source_status)}}}
Command::Quiz{target,path,json:j}=>{let v=zuri_core::quiz(&root(path)?,&target)?;if j{json(&v)?}else{for(i,q)in v.iter().enumerate(){println!("Q{}. {}\n    Answer: {}\n    Evidence: {}\n",i+1,q.question,q.answer,q.evidence)}}}
Command::Doctor{json:j}=>{let v=zuri_core::doctor();if j{json(&v)?}else{println!("CodeSage Zuri Doctor");for(k,v)in v{println!("{k}: {v}")}}}
Command::Model{command}=>match command{ModelCommand::Status=>json(&ModelConfig::load()?.status())?,ModelCommand::Configure{endpoint,model,enabled}=>{ModelConfig{enabled,endpoint,model}.save()?;println!("Saved local model configuration. Deterministic Zuri remains independent.")},ModelCommand::Test=>json(&ModelConfig::load()?.status())?},
Command::Tui{path}=>tui::run(&root(path)?)?};Ok(())}
