use crate::{EvidenceKind,Result,ZuriError};
use directories::ProjectDirs;
use rusqlite::{params,Connection};
use serde::{Deserialize,Serialize};
use std::fs;
use std::path::{Path,PathBuf};
const BUILTIN:&str=include_str!("../assets/python_core.json");
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct KnowledgeEntry{pub entry_id:String,pub topic:String,pub title:String,pub body:String,pub keywords:Vec<String>,pub source_title:String,pub source_url:String,pub source_status:String}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct KnowledgeHit{pub entry:KnowledgeEntry,pub rank:f64,pub evidence:EvidenceKind}
pub struct KnowledgePack{path:PathBuf}
impl KnowledgePack{
 pub fn builtin_path()->Result<PathBuf>{let dirs=ProjectDirs::from("dev","codesage-zuri","CodeSage Zuri").ok_or_else(||ZuriError::Config("cannot determine OS data directory".into()))?;let dir=dirs.data_dir().join("packs");fs::create_dir_all(&dir)?;Ok(dir.join("python-core-0.1.0.zpk"))}
 pub fn ensure_builtin()->Result<Self>{let path=Self::builtin_path()?;if !path.exists(){Self::build_from_json(&path,BUILTIN)?;}Ok(Self{path})}
 pub fn build_from_json(path:&Path,json:&str)->Result<()>{if path.exists(){fs::remove_file(path)?;}if let Some(p)=path.parent(){fs::create_dir_all(p)?;}let mut conn=Connection::open(path)?;conn.execute_batch("CREATE TABLE manifest(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE entries(entry_id TEXT PRIMARY KEY,topic TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,keywords_json TEXT NOT NULL,source_title TEXT NOT NULL,source_url TEXT NOT NULL,source_status TEXT NOT NULL);CREATE VIRTUAL TABLE entries_fts USING fts5(entry_id UNINDEXED,title,topic,body,keywords);")?;conn.execute("INSERT INTO manifest(key,value) VALUES('id','python-core'),('version','0.1.0'),('schema_version','1'),('language','python')",[])?;let entries:Vec<KnowledgeEntry>=serde_json::from_str(json).map_err(|e|ZuriError::Config(e.to_string()))?;let tx=conn.transaction()?;for e in entries{let keywords=e.keywords.join(" ");tx.execute("INSERT INTO entries VALUES(?1,?2,?3,?4,?5,?6,?7,?8)",params![e.entry_id,e.topic,e.title,e.body,serde_json::to_string(&e.keywords).unwrap(),e.source_title,e.source_url,e.source_status])?;tx.execute("INSERT INTO entries_fts(entry_id,title,topic,body,keywords) VALUES(?1,?2,?3,?4,?5)",params![e.entry_id,e.title,e.topic,e.body,keywords])?;}tx.commit()?;Ok(())}
 pub fn path(&self)->&Path{&self.path}
 pub fn search(&self,q:&str,limit:usize)->Result<Vec<KnowledgeHit>>{let conn=Connection::open(&self.path)?;let mut st=conn.prepare("SELECT e.entry_id,e.topic,e.title,e.body,e.keywords_json,e.source_title,e.source_url,e.source_status,bm25(entries_fts) FROM entries_fts JOIN entries e USING(entry_id) WHERE entries_fts MATCH ?1 ORDER BY bm25(entries_fts) LIMIT ?2")?;let rows=st.query_map(params![q,limit as i64],|r|{let keywords:String=r.get(4)?;Ok(KnowledgeHit{entry:KnowledgeEntry{entry_id:r.get(0)?,topic:r.get(1)?,title:r.get(2)?,body:r.get(3)?,keywords:serde_json::from_str(&keywords).unwrap_or_default(),source_title:r.get(5)?,source_url:r.get(6)?,source_status:r.get(7)?},rank:r.get(8)?,evidence:EvidenceKind::Documented})})?;Ok(rows.collect::<rusqlite::Result<_>>()?)}
 pub fn topic(&self,topic:&str)->Result<Vec<KnowledgeEntry>>{let conn=Connection::open(&self.path)?;let mut st=conn.prepare("SELECT entry_id,topic,title,body,keywords_json,source_title,source_url,source_status FROM entries WHERE topic=?1 OR entry_id=?1 ORDER BY title")?;let rows=st.query_map(params![topic],|r|{let keywords:String=r.get(4)?;Ok(KnowledgeEntry{entry_id:r.get(0)?,topic:r.get(1)?,title:r.get(2)?,body:r.get(3)?,keywords:serde_json::from_str(&keywords).unwrap_or_default(),source_title:r.get(5)?,source_url:r.get(6)?,source_status:r.get(7)?})})?;Ok(rows.collect::<rusqlite::Result<_>>()?)}
}
