use crate::{Result,ZuriError};
use directories::ProjectDirs;
use serde::{Deserialize,Serialize};
use std::{fs,io::{Read,Write},net::{TcpStream,ToSocketAddrs},path::PathBuf,time::Duration};
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct ModelConfig{pub enabled:bool,pub endpoint:String,pub model:Option<String>}
impl Default for ModelConfig{fn default()->Self{Self{enabled:false,endpoint:"http://127.0.0.1:8080".into(),model:None}}}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct ModelStatus{pub configured:bool,pub endpoint:String,pub reachable:bool,pub detail:String}
fn config_path()->Result<PathBuf>{let dirs=ProjectDirs::from("dev","codesage-zuri","CodeSage Zuri").ok_or_else(||ZuriError::Config("cannot determine OS config directory".into()))?;fs::create_dir_all(dirs.config_dir())?;Ok(dirs.config_dir().join("model.toml"))}
impl ModelConfig{pub fn load()->Result<Self>{let p=config_path()?;if !p.exists(){return Ok(Self::default())}toml::from_str(&fs::read_to_string(p)?).map_err(|e|ZuriError::Config(e.to_string()))}pub fn save(&self)->Result<()>{let p=config_path()?;let body=toml::to_string_pretty(self).map_err(|e|ZuriError::Config(e.to_string()))?;fs::write(p,body)?;Ok(())}pub fn status(&self)->ModelStatus{if !self.enabled{return ModelStatus{configured:false,endpoint:self.endpoint.clone(),reachable:false,detail:"model enhancement is disabled; deterministic Zuri remains fully available".into()}}match probe_local_http(&self.endpoint){Ok(detail)=>ModelStatus{configured:true,endpoint:self.endpoint.clone(),reachable:true,detail},Err(e)=>ModelStatus{configured:true,endpoint:self.endpoint.clone(),reachable:false,detail:e.to_string()}}}}
fn parse_local_endpoint(endpoint:&str)->Result<(String,u16)>{let rest=endpoint.strip_prefix("http://").ok_or_else(||ZuriError::Config("v0.1 local model endpoint must use http://".into()))?;let authority=rest.split('/').next().unwrap_or(rest);let (host,port)=authority.rsplit_once(':').map(|(h,p)|(h,p.parse::<u16>().unwrap_or(80))).unwrap_or((authority,80));if !matches!(host,"127.0.0.1"|"localhost"){return Err(ZuriError::Config("v0.1 refuses non-local model endpoints by default".into()))}Ok((host.into(),port))}
pub fn probe_local_http(endpoint:&str)->Result<String>{let(host,port)=parse_local_endpoint(endpoint)?;let addr=(host.as_str(),port).to_socket_addrs()?.next().ok_or_else(||ZuriError::Config("cannot resolve local endpoint".into()))?;let mut stream=TcpStream::connect_timeout(&addr,Duration::from_secs(2))?;stream.set_read_timeout(Some(Duration::from_secs(2)))?;stream.write_all(format!("GET /v1/models HTTP/1.1\r\nHost: {host}:{port}\r\nConnection: close\r\n\r\n").as_bytes())?;let mut response=String::new();stream.read_to_string(&mut response)?;Ok(response.lines().next().unwrap_or("no HTTP response").to_string())}
